version: 0.2
phases:
  install:
    commands:
      - cd ABCall
      - npm install -g @angular/cli
      - npm install
    runtime-versions:
      nodejs: 14.x
  build:
    commands:
      - ng build --prod
artifacts:
  files:
    - '**/*'
  base-directory: dist