version: 0.2
  phases:
    install:
      commands:
        - cd ABCall
        - npm install -g @angular/cli
        - npm install
      runtime-versions:
        python: '3.9'
    build:
      commands:
        - ng build --prod
  artifacts:
    files:
      - '**/*'
    base-directory: dist